language: generic
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - git submodule update --init --recursive
  - ./underwater-ros/workspace-prep

install:
  - ./underwater-ros/install-ros
  - ./underwater-ros/install-ceres
  - source ~/.bashrc

script:
  - ./underwater-ros/workspace-setup
  - source ~/.bashrc
  - cd ~/osu-uwrt/riptide_ws
  - catkin_make

notifications:
  email: false
  # slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
